export const ActionTypes = {
  FETCH_FEATURED_PLAYLISTS_REQUEST: "FETCH_FEATURED_PLAYLISTS_REQUEST",
  FETCH_FEATURED_PLAYLISTS_SUCCESS: "FETCH_FEATURED_PLAYLISTS_SUCCESS",
  FETCH_FEATURED_PLAYLISTS_FAILURE: "FETCH_FEATURED_PLAYLISTS_FAILURE",
  FETCH_SPOTIFY_TOKEN_REQUEST: "FETCH_SPOTIFY_TOKEN_REQUEST",
  FETCH_SPOTIFY_TOKEN_SUCCESS: "FETCH_SPOTIFY_TOKEN_SUCCESS",
  FETCH_SPOTIFY_TOKEN_FAILURE: "FETCH_SPOTIFY_TOKEN_FAILURE",
  DROP_ITEM: "DROP_ITEM",
  MOVE_ITEM: "MOVE_ITEM",
  SAVE_USER_PLAYLIST: "FETCH_FEATURED_PLAYLISTS_SUCCESS"


};
